repositories:
  - name: chartmuseum
    url: https://chartmuseum.fitfit.dk
  - name: kubernetes-charts
    url: https://kubernetes-charts.storage.googleapis.com

releases:
#  - name: nginx-ingress
#    namespace: nginx-ingress
#    chart: kubernetes-charts/nginx-ingress
#    set:
#      - name: rbac.create
#        value: true

  - name: whoami
    namespace: whoami
    chart: chartmuseum/whoami-{{ requiredEnv "STAGE" }}
  - name: ip2country
    namespace: ip2country
    chart: chartmuseum/ip2country-{{ requiredEnv "STAGE" }}
  - name: ip2flag
    namespace: ip2flag
    chart: chartmuseum/ip2flag-{{ requiredEnv "STAGE" }}

helmDefaults:
  recreatePods: true
  force: true
